name: 'RickRoll on Failure'
branding:
  icon: 'alert-triangle'  
  color: 'red'
description: 'Post a Rickroll GIF when a workflow fails.'
author: 'Tejasv Sharma'
inputs: 
  GITHUB_TOKEN:
    description: 'Github token of the repository'
    required: false
    default: '${{ github.token }}'
runs:
  using: 'node20' # Updated from node12 as it is deprecated
  main: 'index.js'
